app:
  http:
    cors:
      enabled: true
    proxy:
      proxy-address-forwarding: true
      allow-forwarded: true
  event:
    queue:
      dns: # amqp://guest:guest@localhost:5672/%2f
      topic: lught.events
  rate-limit:
    id: app_global_limit
    policy: sliding_window
    limit: 1500
    interval: 1 minute
    bucket-resolver: Civi\Lughauth\Shared\Infrastructure\Middelware\Rate\BaseBucketResolver
    connection-resolver: Civi\Lughauth\Shared\Infrastructure\Middelware\Rate\IpGranularityResolver
