/management/log-collector:
  api-key-scope: collect
/management/trace-collector:
  api-key-scope: collect
/no-management/entity-changelo-query-ack:
  api-key-scope: sync
/no-management/entity-changelo-query-ask:
  api-key-scope: sync
/no-management:
  roles: ['ROOT']
  # cidr: ['192.168.0.0/24']
  anonimous: false